version: '3.9'
services:
  db:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
